name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Set up Python
      run: uv python install 3.12

    - name: Build package
      run: uv build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

  publish-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Set up Python
      run: uv python install 3.12

    - name: Install dependencies
      run: |
        uv pip install --system -e ".[docs]"

    - name: Build docs
      run: |
        cd docs
        uv run sphinx-build -b html . _build/html

    - name: Trigger ReadTheDocs build
      run: |
        curl -X POST -d "token=${{ secrets.READTHEDOCS_TOKEN }}" https://readthedocs.org/api/v3/projects/django-htmx-tools/versions/latest/builds/
