name: Release

on:
  workflow_dispatch:
    inputs:
      increment:
        description: 'Version increment type'
        required: true
        type: choice
        options:
          - PATCH
          - MINOR
          - MAJOR

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Set up Python
      run: uv python install 3.12

    - name: Create virtual environment and install dependencies
      run: |
        uv venv
        uv pip install -e ".[dev]"

    - name: Configure git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Bump version and update changelog
      run: |
        uv run cz bump --increment ${{ github.event.inputs.increment }}

    - name: Push changes
      run: |
        git push
        git push --tags

    - name: Get version
      id: version
      run: |
        echo "version=$(uv run cz version --project)" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create v${{ steps.version.outputs.version }} \
          --title "v${{ steps.version.outputs.version }}" \
          --notes-from-tag \
          --verify-tag
